### ISSUE TITLE
MyBB 1.8.32 - broken threads

### ISSUE THREAD

**Issue by Eldenroot** [PaulBender/Disable-Post-Edit#1]
After installing and activating this plugin I get this output when I wanna open any thread...

![image](https://user-images.githubusercontent.com/778890/204057366-b331102a-ae8e-458c-9ade-f30b0370b869.png)

**Comment by Eldenroot** [comment]
![image](https://user-images.githubusercontent.com/778890/210180663-e49d3e93-0826-415d-bac7-8c8e43a2e0bf.png)
 please can you fix it" I think it is reated to ASCII

**Comment by Starpaul20** [comment]
Sorry, I haven't been able to reproduce this issue.

**Comment by Eldenroot** [comment]
1.1.1 fixed this! thx!
